"""requirements stage handler.

Baseline run: reuses the requirement normalization already locked in
design-log.md Section 1, since that requirement-understanding work is
human-reviewed and settled upstream of this run — re-deriving it at runtime
would just be theater.

Scenario runs get their own dedicated normalization block, matched by
keyword against the raw requirement text. Anything matching none of them
falls back to a generic wrap rather than failing outright.
"""
from __future__ import annotations

from ..state import RunState

BASELINE_ASSUMPTIONS = [
    "Alias is unique for the lifetime of the system (no reuse, even after a link is deleted).",
    "Fixed-length alias (7 chars, base62) generated by the system; no user-chosen length for v1.",
    "On generation collision: regenerate and retry, bounded to 5 attempts before failing the request.",
    "Analytics tracked: click count, timestamp, and referrer per link; no user auth or per-user dashboards.",
    "Idempotent creation (same long URL returns the same short URL); malformed/malicious URLs rejected; "
    "graceful 404 on unknown/expired aliases.",
    "No link expiration/TTL for v1 — noted as a limitation, reintroduced deliberately in later scenarios.",
]

BASELINE_NORMALIZED = (
    "Build a service that accepts a long URL and returns a shortened, unique alias that redirects to the "
    "original on request, with basic usage analytics per link (click count, timestamp, referrer) and "
    "reliability characteristics appropriate to a public-facing redirect service. Custom aliases, link "
    "expiration, and auth/ownership are out of scope for v1."
)

# --- Greenfield scenario: custom aliases (design-log.md Section 8) --------

CUSTOM_ALIAS_ASSUMPTIONS = [
    "Custom alias format: 3-32 characters, letters/digits/hyphen/underscore only, case-sensitive "
    "(matches the character set already used for generated aliases; base62 is a subset).",
    "A small reserved-word list (currently just 'api') is rejected to avoid confusion with existing "
    "API routes — reserved-word set is expected to grow as new top-level routes are added.",
    "Collision behavior differs from generated aliases on purpose: requesting an already-taken custom "
    "alias for a DIFFERENT long URL returns 409 Conflict rather than silently generating a substitute, "
    "since the caller explicitly asked for that specific alias.",
    "Idempotency for custom aliases is scoped to the exact (alias, long_url) pair, not to long_url alone "
    "— requesting a custom alias for a URL that already has a different alias must NOT silently return "
    "the old alias, or the custom-alias request would appear to silently no-op.",
    "No new endpoint: custom alias is an optional field on the existing POST /api/links, not a separate "
    "API, since it's the same operation (create a link) with an optional extra input.",
]

CUSTOM_ALIAS_NORMALIZED = (
    "Extend link creation (POST /api/links) to accept an optional user-supplied alias instead of only "
    "a system-generated one, while preserving the existing reliability guarantees (validation, "
    "idempotency, graceful conflict handling) for the new field, and introducing conflict (409) as a new "
    "outcome distinct from the existing generation-retry behavior."
)

# --- Brownfield scenario: link expiration/TTL (design-log.md Section 8) ---

TTL_ASSUMPTIONS = [
    "TTL is opt-in per link via an optional ttl_seconds field on creation; omitting it means the link "
    "never expires (backward compatible with every link created before this feature existed).",
    "Expiration is enforced lazily at read-time (on redirect), not via a background sweep job — simplest "
    "reliable approach for a single-process prototype; expired rows are never actively purged, just made "
    "unreachable through the redirect path.",
    "Expired-but-still-present is a distinct outcome from never-existed: the redirect endpoint returns "
    "410 Gone for an expired alias vs 404 Not Found for an unknown one, since a caller might reasonably "
    "want to react differently (410 means don't retry, it's gone for good).",
    "Analytics/stats access is NOT gated by expiration — an owner can still see final click counts for an "
    "expired link; only the redirect (the thing that actually 'uses' the link) is blocked.",
    "Idempotent repeat requests do not extend or change an existing link's expiry — idempotent means "
    "no-op, not 'refresh the TTL'.",
    "Existing DBs created before this feature (no expires_at column) are migrated in place via "
    "ALTER TABLE on startup, not required to be recreated from scratch — this is genuinely brownfield: "
    "an existing data flow being extended, not a fresh table.",
]

TTL_NORMALIZED = (
    "Extend link creation (POST /api/links) to accept an optional ttl_seconds, after which the redirect "
    "endpoint treats the alias as gone (410) while preserving the record and its analytics for read access. "
    "Requires a schema migration for links created under the pre-TTL schema."
)

# --- Ambiguous scenario: "make it more reliable" (design-log.md Section 8) ---
#
# Unlike every scenario above, this raw requirement names no concrete
# feature at all — "reliable" could mean a dozen different things. The
# candidates below are the actual disambiguation reasoning, each recorded
# as its own decision in the run's decision log (not just this comment),
# per the requirement that this reasoning be part of the audit trail a
# reviewer can inspect in state.json, not something that only exists in
# chat or as source commentary.

RELIABILITY_CANDIDATES = [
    # (candidate name, what it is, verdict, why)
    (
        "Concurrent-write availability",
        "Add bounded retry + exponential backoff for SQLite 'database is locked' on the service's write "
        "paths (link creation, click recording).",
        "SELECTED",
        "SQLite's single-writer model makes lock contention a real risk under concurrent load, not a "
        "hypothetical one, and 'availability under load' was already named as a target in design-log.md "
        "Section 1 but never concretely implemented anywhere in the codebase until now.",
    ),
    (
        "Operational health/readiness signal",
        "Add a GET /healthz endpoint that verifies DB connectivity, not just process liveness.",
        "SELECTED",
        "This is a standard reliability primitive for any service meant to run behind a monitor or load "
        "balancer, and the service currently has no way to answer 'is this instance actually healthy?' "
        "at all.",
    ),
    (
        "Structured logging / observability",
        "Add structured request/error logging or a metrics export path.",
        "DEFERRED",
        "Orthogonal to the two concrete gaps above; adding it would mean deciding a log format, "
        "destination, and correlation-ID scheme without a specific failure mode it fixes today. Revisit "
        "if a concrete debugging need arises.",
    ),
    (
        "Circuit breaker / external dependency resilience",
        "Add circuit-breaker logic around downstream service calls.",
        "DEFERRED",
        "Not applicable to this architecture: the service has zero external network dependencies "
        "(SQLite is local and in-process), so this would be solving a failure mode the current system "
        "cannot actually experience.",
    ),
]

RELIABILITY_NORMALIZED = (
    "Ambiguous requirement disambiguated to two concrete, testable reliability improvements: (1) bounded "
    "retry with backoff for SQLite write-lock contention on link creation and click recording, and (2) a "
    "GET /healthz endpoint verifying DB connectivity for operational monitoring. Other candidate "
    "interpretations (structured logging, circuit breakers) were considered and explicitly deferred — "
    "see this run's decision log for the reasoning behind each."
)

RELIABILITY_ASSUMPTIONS = [
    "\"More reliable\" is scoped to availability-under-load and operational monitoring — the two most "
    "concrete, already-named gaps against design-log.md Section 1's own 'availability under load' "
    "target — not treated as a general invitation to add every reliability-adjacent feature.",
    "SQLite write-lock retry uses bounded attempts (3) with exponential backoff, mirroring the same "
    "bounded-retry philosophy already used for alias-generation collisions (shortener.py) and the "
    "orchestration engine itself (orchestrator/retry.py) — an existing pattern applied to a new "
    "transient-failure class, not a new pattern invented for this feature.",
    "/healthz checks DB connectivity (SELECT 1), not just process liveness, since a process that's up "
    "but can't reach its only dependency is not actually healthy for this service's purposes.",
    "/healthz is added to shortener.py's RESERVED_ALIASES (alongside 'api') so a custom alias can never "
    "shadow it — the same reserved-word mechanism the greenfield custom-alias scenario introduced.",
]


def handler(state: RunState) -> None:
    raw = state.requirement.raw.strip()
    raw_lower = raw.lower()

    if "custom alias" in raw_lower:
        state.requirement.normalized = CUSTOM_ALIAS_NORMALIZED
        state.requirement.assumptions = list(CUSTOM_ALIAS_ASSUMPTIONS)
        rationale = "greenfield scenario: custom aliases (design-log.md Section 8)"
    elif "ttl" in raw_lower or "expir" in raw_lower:
        state.requirement.normalized = TTL_NORMALIZED
        state.requirement.assumptions = list(TTL_ASSUMPTIONS)
        state.requirement.requires_migration_review = True
        rationale = "brownfield scenario: link expiration/TTL (design-log.md Section 8)"
    elif "more reliable" in raw_lower or "reliability" in raw_lower:
        state.requirement.normalized = RELIABILITY_NORMALIZED
        state.requirement.assumptions = list(RELIABILITY_ASSUMPTIONS)
        rationale = (
            "ambiguous scenario: the raw requirement names no concrete feature, disambiguated via "
            "explicit candidate analysis — see the [SELECTED]/[DEFERRED] decisions recorded below"
        )
        # This loop IS the disambiguation reasoning the ambiguous scenario is meant to
        # demonstrate — each candidate becomes its own entry in state.decisions, inspectable
        # in state.json, not just narrated in a comment or in chat.
        for name, description, verdict, why in RELIABILITY_CANDIDATES:
            state.add_decision(
                stage="requirements",
                decision=f"[{verdict}] {name}: {description}",
                rationale=why,
                actor="agent",
            )
    elif not raw or "url shortener" in raw_lower or "core apis" in raw_lower:
        state.requirement.normalized = BASELINE_NORMALIZED
        state.requirement.assumptions = list(BASELINE_ASSUMPTIONS)
        rationale = "matches the baseline v1 scope already normalized in design-log.md Section 1"
    else:
        state.requirement.normalized = f"Normalized: {raw}"
        state.requirement.assumptions = [f"generic fallback normalization applied to: {raw!r}"]
        rationale = "raw requirement text doesn't match any known scenario phrasing; generic fallback used"

    state.add_decision(
        stage="requirements",
        decision="requirement normalized",
        rationale=rationale,
        actor="agent",
    )
