"""requirements stage handler.

Baseline run: reuses the requirement normalization already locked in
design-log.md Section 1, since that requirement-understanding work is
human-reviewed and settled upstream of this run — re-deriving it at runtime
would just be theater.

Scenario runs get their own dedicated normalization block, matched by
keyword against the raw requirement text. Anything matching none of them
falls back to a generic wrap rather than failing outright.
"""
from __future__ import annotations

from ..state import RunState

BASELINE_ASSUMPTIONS = [
    "Alias is unique for the lifetime of the system (no reuse, even after a link is deleted).",
    "Fixed-length alias (7 chars, base62) generated by the system; no user-chosen length for v1.",
    "On generation collision: regenerate and retry, bounded to 5 attempts before failing the request.",
    "Analytics tracked: click count, timestamp, and referrer per link; no user auth or per-user dashboards.",
    "Idempotent creation (same long URL returns the same short URL); malformed/malicious URLs rejected; "
    "graceful 404 on unknown/expired aliases.",
    "No link expiration/TTL for v1 — noted as a limitation, reintroduced deliberately in later scenarios.",
]

BASELINE_NORMALIZED = (
    "Build a service that accepts a long URL and returns a shortened, unique alias that redirects to the "
    "original on request, with basic usage analytics per link (click count, timestamp, referrer) and "
    "reliability characteristics appropriate to a public-facing redirect service. Custom aliases, link "
    "expiration, and auth/ownership are out of scope for v1."
)

# --- Greenfield scenario: custom aliases (design-log.md Section 8) --------

CUSTOM_ALIAS_ASSUMPTIONS = [
    "Custom alias format: 3-32 characters, letters/digits/hyphen/underscore only, case-sensitive "
    "(matches the character set already used for generated aliases; base62 is a subset).",
    "A small reserved-word list (currently just 'api') is rejected to avoid confusion with existing "
    "API routes — reserved-word set is expected to grow as new top-level routes are added.",
    "Collision behavior differs from generated aliases on purpose: requesting an already-taken custom "
    "alias for a DIFFERENT long URL returns 409 Conflict rather than silently generating a substitute, "
    "since the caller explicitly asked for that specific alias.",
    "Idempotency for custom aliases is scoped to the exact (alias, long_url) pair, not to long_url alone "
    "— requesting a custom alias for a URL that already has a different alias must NOT silently return "
    "the old alias, or the custom-alias request would appear to silently no-op.",
    "No new endpoint: custom alias is an optional field on the existing POST /api/links, not a separate "
    "API, since it's the same operation (create a link) with an optional extra input.",
]

CUSTOM_ALIAS_NORMALIZED = (
    "Extend link creation (POST /api/links) to accept an optional user-supplied alias instead of only "
    "a system-generated one, while preserving the existing reliability guarantees (validation, "
    "idempotency, graceful conflict handling) for the new field, and introducing conflict (409) as a new "
    "outcome distinct from the existing generation-retry behavior."
)


def handler(state: RunState) -> None:
    raw = state.requirement.raw.strip()
    raw_lower = raw.lower()

    if "custom alias" in raw_lower:
        state.requirement.normalized = CUSTOM_ALIAS_NORMALIZED
        state.requirement.assumptions = list(CUSTOM_ALIAS_ASSUMPTIONS)
        rationale = "greenfield scenario: custom aliases (design-log.md Section 8)"
    elif not raw or "url shortener" in raw_lower or "core apis" in raw_lower:
        state.requirement.normalized = BASELINE_NORMALIZED
        state.requirement.assumptions = list(BASELINE_ASSUMPTIONS)
        rationale = "matches the baseline v1 scope already normalized in design-log.md Section 1"
    else:
        state.requirement.normalized = f"Normalized: {raw}"
        state.requirement.assumptions = [f"generic fallback normalization applied to: {raw!r}"]
        rationale = "raw requirement text doesn't match any known scenario phrasing; generic fallback used"

    state.add_decision(
        stage="requirements",
        decision="requirement normalized",
        rationale=rationale,
        actor="agent",
    )
